import re
import reprlib

RE_WORD = re.compile(r"\w+")

class Sentence:

    def __init__(self, text):
        self.text = text
        # .findall returns a list of all nonoverlapping matches of the regular
        # expression as a list of strings
        self.words = RE_WORD.findall(text)

    def __getitem__(self, index):
        # self.words holds the result of .findall so return the word at index
        return self.words[index]

    # No required to make an iterable, but put for sake of completeness of the
    # sequence protocol
    def __len__(self):
        return len(self.words)

    def __repr__(self):
        return "Sentence(%s)" % reprlib.repr(self.text)

"""
s = Sentence('"The time has come," the Walrus said,')
s       # Sentence('"The time has...Walrus said,') - generated by reprlib.repr

for word in s:      # The time has come the Walrus said
    print(word)
list(s)             # ['The', 'time', 'has', 'come', 'the', 'walrus', 'said']

print(s[0], s[-1])  # The, said

isinstance(s, abc.Iterable) # False
"""